### ISSUE TITLE
Missing dependency for jsonschema

### ISSUE THREAD

**Issue by ghost** [kerfab/jdic#1]
Ubuntu Mate 1.18 (Artful Aardvark + updates) running Python 3.6.3. Stock 3.6.3 installation didn't have the _jsonschema_ package installed by default and it wasn't otherwise identified as a dependency. After `pip install jdic`:
```
$ ./dechat.py
Traceback (most recent call last):
  File "./dechat.py", line 3, in <module>
    from jdic import jdic
  File "/home/gnuser/Learn/Python/dechat/lib/python3.6/site-packages/jdic/__init__.py", line 4, in <module>
    from .jdic import \
  File "/home/gnuser/Learn/Python/dechat/lib/python3.6/site-packages/jdic/jdic.py", line 10, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```
After `$ pip install jsonschema`, I get the desired output:
```
$ ./dechat.py
data.385099551398166529.386372354156134400.u
data.385099551398166529.386570115467968513.u
. . .
```
I'd submit a patch if I knew where to express the dependency.

**Comment by kerfab** [comment]
Hello, I will investigate that packaging issue when I have a few moment, thank you for your help.
